import React, { useEffect, useMemo, useState } from "react";
//Partially generated by AI + Serge BEN YAMIN from BPCE VIE
function readHostData(currentHost) {
  // this function first checks if there is data in the tooloutput and sends it
  // otherwise it sends either toolOutput or structuredContent
  const host = currentHost || window.openai || {};
  console.log("current host : ", currentHost);
  const toolOutput = host.toolOutput;
  console.log("tool output : " , toolOutput)
  if (toolOutput && typeof toolOutput === "object" && "data" in toolOutput) {
    return toolOutput.data || {};
  }
  console.log("structured content : " , host.structuredContent);
  console.log("widget state : ", host.widgetState);
  console.log("window app data : ",window.__APP_DATA__  );
  return (
    toolOutput ||
    host.structuredContent ||
    host.widgetState ||
    window.__APP_DATA__ ||
    {}
  );
}

export default function App({ data, debug = false, host = null }) {

  const [liveHost, setLiveHost] = useState(host || window.openai || null);
  const [liveData, setLiveData] = useState(data || {});

  useEffect(() => {
    //so here handleUpdate fetches the dictionary-like in python object with the data in 
    // for example 
    //     {
    //   age: "24",
    //   versement_initial: "1 000.00",
    //   duree_investissment: "14",
    //   niveau_risque: "2",
    //   overall_gain: "608.44",
    //   conditions_generales: "..."
    // }
    const handleUpdate = () => {
      const nextHost = window.openai || null;
      setLiveHost(nextHost);
      setLiveData(readHostData(nextHost));
    };
    // notify the widget when the data arrives from whatever is already in window.openai
    handleUpdate();
    // the widget catches future updates when chagpt injects data later
    window.addEventListener("openai:set_globals", handleUpdate);
    
    return () => window.removeEventListener("openai:set_globals", handleUpdate);
  }, []);


  // fallback to default values so the UI doesn't crash
  const {
    age = "-",
    versement_initial = "-",
    duree_investissment = "-",
    niveau_risque = "-",
    overall_gain = "-",
    conditions_generales = "",
    intent = "",
  } = liveData || {};

  // const isReady = useMemo(() => {
  //   const required = {
  //     age,
  //     versement_initial,
  //     duree_investissment,
  //     niveau_risque,
  //     overall_gain,
  //   };
  //   //Takes all required values (age, versement_initial, etc.)
  // //.every(...) returns true only if every value passes the conditions
  //   return Object.values(required).every((value) => {
  //     if (value === null || value === undefined) return false;
  //     if (typeof value !== "string") return true;
  //     const trimmed = value.trim();
  //     return trimmed !== "" && trimmed !== "-" && trimmed !== "—";
  //   });
  // }, [age, versement_initial, duree_investissment, niveau_risque, overall_gain]);

  // helper function we check if the data is here or not , remember there is a default "-" we 
  // to check if it is not default value
  const isValid = (value) => {
    if (value === null || value === undefined) return false;
    const trimmed = String(value).trim();
    return trimmed !== "" && trimmed !== "-" && trimmed !== "???";
  };

  //useMemo caches the result of a computation and recomputes it only if one of the data changes
  // so isReady is recomputed only if every data is valid
  const isReady = useMemo(
    () =>
      [age, versement_initial, duree_investissment, niveau_risque, overall_gain].every(isValid),
    // dependency array , recomputes only if one of these value changes
    [age, versement_initial, duree_investissment, niveau_risque, overall_gain]
  );

  if (!debug && intent && intent !== "simulation") {
    return null;
  }

  if (!isReady && !debug) {
    return null;
  }

  return (
    <div className="page">
      <header className="hero">
        <div>
          <p className="eyebrow">Amazing Life Insurance Company</p>
          <h1>Simulation PERI</h1>
          <p className="sub">
            Resumé de la simulation et projection des gains. 
          </p>
        </div>
        <div className="badge">
          <div className="badge-label">Gain estime</div>
          <div className="badge-value">{overall_gain} EUR</div>
        </div>
      </header>

      <section className="panel">
        <h2>Profil client</h2>
        <div className="grid">
          <div className="card">
            <div className="label">Age</div>
            <div className="value">{age} ans</div>
          </div>
          <div className="card">
            <div className="label">Versement initial</div>
            <div className="value">{versement_initial} EUR</div>
          </div>
          <div className="card">
            <div className="label">Duree d'investissement</div>
            <div className="value">{duree_investissment} ans</div>
          </div>
          <div className="card">
            <div className="label">Niveau de risque</div>
            <div className="value">{niveau_risque} / 10</div>
          </div>
        </div>
      </section>

      <section className="panel">
        <h2>Performance financiere</h2>
        <div className="highlight">
          <div className="highlight-title">Gain total estime</div>
          <div className="highlight-value">
            {overall_gain} EUR sur {duree_investissment} ans
          </div>
          <div className="highlight-note">
            Resultat indicatif, a valider avec votre conseiller.
          </div>
        </div>
      </section>

      <section className="panel">
        <h2>Conditions generales</h2>
        <div className="conditions">{conditions_generales}</div>
      </section>

      {debug ? (
        <section className="panel">
          <h2>Debug (host)</h2>
          <pre className="debug">
            {JSON.stringify({ data: liveData, host: liveHost }, null, 2)}
          </pre>
        </section>
      ) : null}
    </div>
  );
}
